### PR TITLE
Feature/user can delete idea

### PR DESCRIPTION
**Pull request by qlaire**
__Description of Change(s) Introduced:__ a non-facilitator user can now delete their own idea, but not after 5 seconds of the idea being on the board

__Dependencies Introduced or Upgraded:__ 

- ~~[moment.js](https://momentjs.com/) - 2.18.1~~
  - __for posterity:__ avoided the introduction of moment! [see comment below](https://github.com/stride-nyc/remote_retro/pull/216#issuecomment-318904493)

__Description of Testing Applied:__ tests for appearance of delete button, and setTimeout for getting rid of delete button

__Relevant github Issue:__ 

#35

### CODE REVIEW

**Comment by vanderhoop** [comment]
Hey Claire, nice work. Two minor blockers to getting this in:

1) no need to bring in moment.js, as there's [a native js method for working with UTC](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC). By leveraging it, we can put off adding a clientside dependency

2) we can avoid the complexity of the setTimeout and rerender by using raw css to make the delete button disappear after 5 seconds: https://stackoverflow.com/questions/21993661/css-auto-hide-elements-after-5-seconds. This has the added benefit of reusability across the app if we want to limit functionality to a window of time.

**Comment by samdec11** [comment]
@vanderhoop Can you explain how to get from the ecto date string to a usable set of inputs for `Date.UTC`? That function's parameters are year, month, day, etc. and not a date string. We couldn't find a workable solution without Moment.

**Comment by vanderhoop** [comment]
@samdec11 @qlaire I'd totally forgotten about this, but I faced a similar problem when only wanting to display the `ShareRetroLinkModal` to users who join within 5s of the retro's creation, and rather than do a bunch of JavaScript to make the value easily comparable, I changed the timestamp value further upstream, so that Phoenix would just give me a UTC datestring that I needed:

```elixir
  # web/models/retro.ex
  schema "retros" do
    # ...

    timestamps(type: :utc_datetime)
  end
```

This allowed me to pass the value in the way that the JavaScript `Date` constructor could digest in one go.
```es6
// web/static/js/components/share_retro_link_modal.jsx
const timeElapsedLessThanFiveSec = retroCreationTimestamp => {
  const millisecondsSinceRetroCreation = new Date(retroCreationTimestamp)
  const timeElapsedSinceRetroCreation = new Date().getTime() - millisecondsSinceRetroCreation
  return (timeElapsedSinceRetroCreation < 5000)
}
```

Note that if we made this change to the `Idea` model (joining the `Retro` model), it begs the question of whether *all* Phoenix models should just use `utc_datestring` timestamp for consistency.

**Comment by qlaire** [comment]
@vanderhoop I got ride of the setTimeout and added the CSS animation. Thanks for the link!

I think it makes sense to be consistent across the the models and use utc_datetime, so I changed them all.

**Comment by vanderhoop** [comment]
f*ck yes: mergin!

**Pull request merged**
