### PR TITLE
WIP: update dependencies

### PR DESCRIPTION
**Pull request by nicholalexander**
__Description of Change(s) Introduced:__ 
`mix deps.update --all`

I noticed Credo was broken because it was an old version.  I updated all the deps just to see what would happen and all the tests were fine.

### CODE REVIEW

**Comment by nicholalexander** [comment]
@vanderhoop - if this looks worth it, i'll figure out whats going on with circle.  lemme know.

**Comment by vanderhoop** [comment]
issue seems to be with the version of elixir required by ecto. for now, let's just bump Credo, as we'll to need to bump the `.tool-versions` file so that circle and heroku are on the latest version, and that'll be a story unto itself. to that end, we'll also want to make sure that all devs are locked in at a given version, so there aren't these weird discrepancies between dev, circle ci, and prod

**Comment by vanderhoop** [comment]
for what it's worth, open a branch to see if elixir 1.6.2 would work fine on circle: https://circleci.com/gh/stride-nyc/remote_retro/1073

**Comment by vanderhoop** [comment]
Hey @nicholalexander, closing this PR due to atrophy. But if you want to pick it back up, feel free to re-open!

**Pull request closed without merging**
